snitch-org/snitch

CMakeLists.txt, README.md, include/snatch/snatch.hpp, src/snatch.cpp
This PR does:
- Add `SNATCH_WITH_EXCEPTIONS` to enable/disable exceptions in the implementation.
- Add guards to disable `try`/`catch` blocks when exceptions are not available.
- Add `SNATCH_WITH_SHORTHAND_MACROS` to enable short macro names, otherwise use `SNATCH_` prefix.
- Show number of skipped tests in the final report.
=> Add SNATCH_WITH_EXCEPTIONS, improve API, and reporting of skipped tests

CMakeLists.txt, README.md, cmake/Findsnatch.cmake, cmake/snatch-config.cmake.in, src/snatch.cpp
This PR does:
- Add CMake install script to create the `.config` file.
- Add a `Findsnatch.cmake` module.
- Update benchmarks to include _doctest_.
- Remove a leftover reference to cxxopts.
=> CMake configuration and benchmark update

CMakeLists.txt, README.md, include/snatch/snatch.hpp, include/snatch/snatch_teamcity.hpp, src/snatch.cpp
For #8:
- Add a new member to `registry`, `with_color`, which is `true` if color should be used in messages and `false` otherwise.
- Add a new command line parameter `--color`, to enable/disable color in messages.
- Add a new configuration pre-processor variable `SNATCH_DEFAULT_WITH_COLOR` to change the default behavior of _snatch_ regarding whether color codes are used in the standard output. Custom reporters may be affected by this variable if they choose to use `registry::with_color`.
For #6:
- Promoted `registry::verbose` from a boolean to an enum similar to _Catch2_. Custom reports may be affected by this variable if they choose to use it.
- Added `snatch::event` namespace, events, and the `data` type to hold all possible events.
- Added …
=> Add support for custom reporters and disabling colors

CMakeLists.txt, README.md, include/snatch/snatch.hpp, include/snatch/snatch_teamcity.hpp, src/snatch.cpp
Bug fixes:
- Fixed `SNATCH_DEFAULT_WITH_COLOR` not honored.
- Fixed error message displayed when nesting sections too deep not using the usual format.
- Fixed "missing semicolon" error in warning disabling macros when placeholders are used.
Miscellaneous changes:
- Added `SNATCH_WITH_TIMINGS` to enable/disable test timing (enabled by default).
- (internal) Moved all test state into a new struct `test_run`, instantiated when a test is run, rather than in the persistent `test_case`. This reduces binary size, results in minor speed up, and simplifies the code a bit.
=> Add `SNATCH_WITH_TIMINGS` plus bug fixes and performance improvements

.github/workflows/cmake.yml, CMakeLists.txt, README.md, include/snatch/snatch.hpp, include/snatch/snatch_teamcity.hpp, src/snatch.cpp
For #9.
- Added `CAPTURE()` and `INFO()`.
Miscellaneous changes:
- Clarify the way in which custom types can be made serializable, and added documentation to README.
=> Add `CAPTURE()` and `INFO()`

README.md, include/snatch/snatch.hpp, tests/CMakeLists.txt, tests/runtime_tests/check.cpp, tests/runtime_tests/matchers.cpp, tests/runtime_tests/small_function.cpp, tests/runtime_tests/string_utility.cpp
Bug fixes:
- Fixed `REQUIRE()` and `CHECK()` not able to use custom `append()` function if the function is not declared in the `snatch::` namespace.
- Fixed `snatch::matchers::with_what_contains` matching too eagerly for `match()`, which resulted in ambiguous comparison operator.
- Fixed incorrect formatting in `snatch::matchers::is_any_of::describe_match`.
Miscelaneous changes:
- (utility) Added support for stateful lambdas to `small_function`.
- (tests) Added tests for `SNATCH_CHECK` and expanded existing tests for more corner cases.
- (internal) Don't refer to global test registry unless absolutely necessary in test macros.
=> Add more tests

.github/workflows/cmake.yml, README.md, include/snatch/snatch.hpp, include/snatch/snatch_config.hpp.config, src/snatch.cpp, tests/CMakeLists.txt, tests/runtime_tests/capture.cpp, tests/runtime_tests/check.cpp, tests/runtime_tests/section.cpp, tests/runtime_tests/skip.cpp, tests/testing.hpp, tests/testing_event.cpp, tests/testing_event.hpp
Other miscellaneous changes:
- `snatch.hpp` now includes `snatch_config.hpp` to reduce the risk of mismatched configuration with implementation.
- (docs) Added example CMake usage instructions.
- (docs) Clarified what happens when a test with sections is aborted.
- (tests) Added tests for `SECTION()`, `CAPTURE()`, `INFO()`, and `SKIP()`.
- (CI) Let all tests run even if some failed.
=> Added tests for capture, section, and skip

README.md, codecov.yaml, include/snatch/snatch.hpp, tests/runtime_tests/registry.cpp, tests/runtime_tests/small_function.cpp
- Fixes #25.
- Update benchmarks for other testing libraries, to use more recent versions, and provide the code.
=> Do not hard-code `std::tuple` as type list

README.md, include/snatch/snatch.hpp, src/snatch.cpp, tests/runtime_tests/capture.cpp, tests/runtime_tests/check.cpp, tests/runtime_tests/registry.cpp, tests/runtime_tests/section.cpp, tests/runtime_tests/skip.cpp
This PR changes the internal implementation of the test macros (`REQUIRE(...)` etc) so they refer to a `thread_local` instance of `test_run`, rather than rely on it being available in the current scope as `SNATCH_CURRENT_TEST` (which, previously, was provided as an argument of the test case). This allows using the test macros in other functions, not only in the immediate scope of the test case.
This has a small performance hit, which was deemed acceptable given the benefits.
Closes #31.
=> Allow test macros in other functions

.github/workflows/cmake.yml, README.md, include/snatch/snatch.hpp, src/snatch.cpp, tests/runtime_tests/registry.cpp
- Remove un-initialised data in `small_vector` and `small_string`, which removes all chances of undefined behavior (UB). The potential UB was preventing these classes from being used in `constexpr` settings. Closes #17.
- When exceptions are disabled, all `REQUIRE*()` and `FAIL()` macros will call `std::terminate` instead of `return`, to ensure no further code in the test case is executed.
=> Add full `constexpr` support for `small_vector` and `small_string`

README.md, include/snatch/snatch.hpp, tests/runtime_tests/check.cpp, tests/testing.hpp
This PR improves the `REQUIRE*()` and `CHECK*()` macros so that all expressions (contextually convertible to bool, as in `if (expr)`) are supported, even if they cannot be decomposed.
Closes #43.
=> Allow `REQUIRE()` and `CHECK()` even on non-decomposable expressions

include/snitch/snitch.hpp, src/snitch.cpp, tests/CMakeLists.txt, tests/runtime_tests/check.cpp, tests/runtime_tests/macros.cpp, tests/runtime_tests/registry.cpp, tests/runtime_tests/regressions.cpp, tests/runtime_tests/section.cpp, tests/runtime_tests/small_string.cpp, tests/runtime_tests/small_vector.cpp, tests/testing.hpp, tests/testing_event.cpp, tests/testing_event.hpp
- Add support for using `REQUIRE()`/`CHECK()` macros on expressions containing bitwise operators (`&`, `|`, `^`), and  assignments (`=`, `+=`, etc.).
- Add missing information to the test events (success/failure/skipped flag and assertion count for `test_case_ended`, and duration for `test_run_ended`).
- Enable tests for using `small_string` and `small_vector` in `constexpr` context.
- Some internal refactoring to use clearer names.
=> Add support for more operators in check macros

README.md, doc/comparison_catch2.md, include/snitch/snitch.hpp, tests/runtime_tests/macros.cpp, tests/testing.hpp
This PR adds macros to support test fixtures, for the more traditional set-up/tear-down layout.
=> Added support for fixtures

CMakeLists.txt, make_snitch_all.py
This PR ports the creation of `snitch_all.hpp` from CMake to Python, so the header can be produced without CMake. This will help adding support for other build system (see #54).
=> Extract creation of snitch_all.hpp into Python script

include/snitch/snitch.hpp, src/snitch.cpp, tests/CMakeLists.txt, tests/runtime_tests/macros.cpp
- Fixes #61 
- Fixes #66 
- Fixes #67 
- Fixes #68
=> Fix several bugs related to macro expansions

src/snitch.cpp, tests/runtime_tests/registry.cpp, tests/testing_event.cpp
- Closes #62.
- Closes #74.
- Added missing test code for custom reporter.
=> Fix absolute paths in library and missing tests

README.md, doc/comparison_catch2.md, include/snitch/snitch_macros_exceptions.hpp, tests/runtime_tests/check.cpp
- Implement `REQUIRE_NOTHROW`/`CHECK_NOTHROW` for #96.
- Fix warnings in `REQUIRE_THROW_*`/`CHECK_THROW_*` when the tested expression returns a value with `[[nodiscard]]`.
=> Implement CHECK_NOTHROW

include/snitch/snitch_function.hpp, tests/runtime_tests/small_function.cpp, tests/testing_assertions.hpp, tests/testing_event.hpp
- Fixed the copy construction of `small_function`. It would fail as "ambiguous" when passing a non-const reference to a `small_function` object, because of the other constructors. This is now all done properly with concepts. #105 
- Fixed a test error in `assertion_exception_enabler`, which wasn't resetting the assertion handler correctly.
=> Fix copy construction of `small_function` and error in tests

.github/workflows/cmake.yml, CMakeLists.txt, tests/CMakeLists.txt
This help ConanCenter, which is running 3.18.2. We actually need 3.20, but only for building the tests. For building the library, 3.14 is enough.
Also closes #120 and turns on CMake warnings as errors in CI, so we catch these in the future.
=> Lower required CMake version for library build

doc/coding_guidelines.md, include/snitch/snitch_cli.hpp, include/snitch/snitch_error_handling.hpp, include/snitch/snitch_function.hpp, include/snitch/snitch_registry.hpp, src/snitch_cli.cpp, src/snitch_error_handling.cpp, src/snitch_registry.cpp, tests/CMakeLists.txt, tests/runtime_tests/function_ref.cpp, tests/testing_assertions.hpp, tests/testing_event.hpp
=> Rename `small_function` to `function_ref`

.github/workflows/meson.yml, meson.build
The PR is related to one of the issues in #116 
> If compiling the library with GCC or clang, we should set -fvisibility=hidden -fvisibility-inlines-hidden (only when building the library, not when consuming it).
=> Set -fvisibility=hidden and -fvisibility-inlines-hidden for Meson

include/snitch/snitch_macros_exceptions.hpp, tests/runtime_tests/check.cpp
=> Fix double error reported when a REQUIRE_THROWS* fails for lack of exception being thrown

include/snitch/snitch_macros_consteval.hpp
=> Fix consteval checks for non-decomposable expressions being evaluated at run time

README.md, include/snitch/snitch_cli.hpp, src/snitch_cli.cpp, src/snitch_registry.cpp, tests/runtime_tests/cli.cpp, tests/runtime_tests/registry.cpp, tests/testing.cpp, tests/testing.hpp
This PR fixes #147:
- The `registry` class now forwards its `with_color` option to the `print_help()` function, so `./tests --color never --help` prints the help text without color codes.
- The command-line parser now parses arguments in two passes. The first pass looks only at color options, silently ignoring any problem, then changes the color configuration as specified. The second pass looks again at all options, and reports any problem using the color options configured in the first pass. This means that, for example, `./tests --color never --verbosity babbling` will report the unknown `babbling` value without using color codes.
Note that, in both cases, argument ordering remains irrelevant, so `--color never --help` and `--help --color never` produces the same output.
=> Fix color codes used even when `--color never` is specified

tests/runtime_tests/check.cpp
For #140, which still affects MSVC 19.38.
=> Disable spaceship test for MSVC 19.38

CMakeLists.txt, include/snitch/snitch_config.hpp.config, meson_options.txt, snitch/meson.build, src/snitch_test_data.cpp
thread local variables will trigger a memory allocation on a bare metal system. When running tests on a single thread, or a system without threads, there is no benefit to using a `thread_local` variable. As discussed in  #158.
This change creates a feature flag to control if snitch should be compiled with support for threading. A macro `SNITCH_THREAD_LOCAL` is defined in the config header that resolves to nothing when the feature flag is disabled, or `thread_local` when it is enabled. The feature flag is enabled by default to preserve existing behavior.
I names the feature flag `SNITCH_WITH_MULTITHREADING` to let it be used for any future threading features as well. If you want a more granular option that is an easy change.
I updated the CMake project file, and the meson options. I don't …
=> feature switch for thread_local variables and multi-threading

src/snitch_reporter_console.cpp, tests/approval_tests/data/expected/reporter_console_list_tests, tests/runtime_tests/registry.cpp
My team uses Clion and while transitioning our libraries to snitch from Catch2 I noticed CLion choking on the tests. Clion has built in Catch2 support, and in the readme snitch claims to support Clion via this.
I modified the snitch main function to write the value of `argv` to a file, and saw that clion calls the test binary twice:
- before running tests with `--list-tests --order lex ~[.]`
- run the tests with `-r xml -d yes --order lex`
I compared the output with the list tests command between the latest Catch2 and snitch. I copied a representation of the difference at the bottom of this description. But the key differences are:
1. tests aren't ordered
2. no header text "Matching test cases:"
3. no final "132 matching test cases"
4. test names aren't indented
5. no tags output for each …
=> Match output of catch2 when listing tests with default reporter

include/snitch/snitch_registry.hpp, include/snitch/snitch_reporter_console.hpp, src/snitch_registry.cpp, src/snitch_reporter_console.cpp, tests/approval_tests/data/expected/reporter_console_list_tests, tests/approval_tests/reporter_console.cpp, tests/runtime_tests/check.cpp, tests/runtime_tests/registry.cpp, tests/runtime_tests/section.cpp, tests/testing_event.cpp
This MR changes the console reporter from free functions to a struct, so that it can maintain state and count the
tests when listing them.
I am stuck trying to figure out how to properly initialize the `report_callback` in the registry. When the console report function was a free function it could just get a reference to that function. But now that it is a struct there needs to be an instance somewhere. The registry is `constinit` so there shouldn't be a static order issue, but it also can't have a non `constexpr` constructor.
Some tests also required a reporter instance, and there I declared one either in the test function itself or in an anonymous namespace in the test file if the lifetime needed to outlast the spot it was used.
=> Catch2 emulation: list tests has a footer

codecov.yml, include/snitch/snitch_capture.hpp, include/snitch/snitch_string_utility.hpp, include/snitch/snitch_test_data.hpp, src/snitch_capture.cpp, src/snitch_registry.cpp, src/snitch_section.cpp, src/snitch_test_data.cpp, tests/runtime_tests/capture.cpp, tests/runtime_tests/section.cpp
- Fix #177 by checking for unhandled exception before popping capture data that goes out of scope. This also affected `SECTION`.
- Add explicit casts in internal code to avoid potential ambiguous calls to `append()` when user defines their own overloads.
- Fix the codecov configuration.
=> Fix capture/section state after unhandled exception(s)

.github/workflows/cmake.yml, CMakeLists.txt, README.md, meson.build
This is just a maintenance PR:
- Fix the CI scripts not running anymore after GitHub stopped supporting `upload-artifact/v2`.
- Fix TOC link in README not using auto-link.
- Update benchmarks (not updated for a while).
- Update version number in preparation for next release.
=> Fix CI and update readme

.gitignore, include/snitch/snitch_reporter_catch2_xml.hpp, include/snitch/snitch_reporter_teamcity.hpp, snitch.sublime-project, src/snitch_reporter_catch2_xml.cpp, src/snitch_reporter_teamcity.cpp
=> Fix reporters not being disabled when requested

include/snitch/snitch_append.hpp, tests/runtime_tests/string_utility.cpp
=> Fix rare invalid output in float to string conversion

CMakeLists.txt
=> Fix CMake install prefix when not set at configure time

CMakeLists.txt, meson.build, tests/install_tests/standalone.cpp
Closes https://github.com/snitch-org/snitch/issues/199.
=> Fix CE due to missing snitch_main.hpp

.github/workflows/cmake.yml, .github/workflows/meson.yml, .github/workflows/release.yml, CMakeLists.txt, meson.build
This is related to https://github.com/snitch-org/snitch/issues/175.
I am not sure how the release artifacts are prepared (the single-file header-only one I think I can figure out) or whether the zip file inside of zip file is intentional, but this workflow should allow performing the necessary steps to automate the upload of release artifacts.
It will execute automatically on published release.
The "Prepare artifacts" step can be used to generate the necessary zip files. The "Upload artifacts" step can be used to upload the prepared files. `with.files` can be filled like this:
```
with:
files: |
snitch-header-only.zip
snitch-ubuntu64-libc++-static.zip
snitch-ubuntu64-libstdc++-static.zip
```
=> Add base for workflow uploading release artifacts

CMakeLists.txt
In Arch,
* the BSL-1.0 license is already installed by package 'licenses'
* the default docs path is /usr/share/doc
=> Allow to not install the license
